# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: FoD SAST Scan (with Aviator)

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v4
      with:
        ref: 'main'
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run FoD SAST Scan
      uses: fortify/github-action/fod-sast-scan@v1
      env:
        FOD_URL: https://ams.fortify.com
        FOD_RELEASE: ${{ secrets.FOD_RELEASE_ID_WITH_AVIATOR }}
        FOD_CLIENT_ID: ${{ secrets.FOD_API_KEY }}
        FOD_CLIENT_SECRET: ${{ secrets.FOD_API_SECRET }}
        EXTRA_PACKAGE_OPTS: -bt mvn
        DO_WAIT: true
        DO_EXPORT: true
